### ISSUE TITLE
I am implementing SEO

### ISSUE THREAD

**Issue by OskarMast** [OskarMast/my-portfolio#16]
- Meta Tags
Meta tags provide information about the webpage to search engines. The most important ones for SEO include the `<title>` tag, `<meta description>`, and `<meta keywords>`.
Example:
```
<head>
    <title>Your Page Title</title>
    <meta name="description" content="Description of your page">
    <meta name="keywords" content="keywords, separated, by, commas">
</head>
```
- URL Structure
Use descriptive, keyword-rich URLs that accurately reflect the content of the page. Avoid using generic or meaningless URLs.
Example:
```
https://www.example.com/blog/seo-best-practices
```
- Heading Tags
Use `<h1>`, `<h2>`, `<h3>`, etc., tags to structure your content. Include relevant keywords in your headings to improve SEO.
Example:
```
<h1>Main Heading</h1>
<h2>Subheading</h2>
```
- Image Optimization
Use descriptive filenames and alt attributes for images. This helps search engines understand the content of the image.
Example:
```
<img src="example.jpg" alt="Descriptive image title">
```
- Content Quality
Publish high-quality, relevant content that provides value to your audience. Use keywords naturally throughout your content.
```
<p>This is a paragraph containing relevant keywords.</p>
```
- Mobile Optimization
Ensure your website is responsive and optimized for mobile devices. Google prioritizes mobile-friendly websites in search results.
- Schema Markup
Use structured data markup (Schema.org) to provide additional information about your content to search engines.
Example:
```
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Article",
  "headline": "Article headline",
  "author": "John Doe",
  "datePublished": "2019-10-12",
  "image": "http://example.com/article.jpg",
  "articleBody": "Article content goes here."
}
</script>
```
- XML Sitemap
Create an XML sitemap and submit it to search engines to help them crawl and index your website more efficiently.
Example:
```
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>https://www.example.com/page1</loc>
        <lastmod>2024-03-11</lastmod>
        <changefreq>monthly</changefreq>
        <priority>0.8</priority>
    </url>
    <!-- Other URLs -->
</urlset>
```

**Comment by dancerking** [comment]
Good.
